INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Petronas','Mercedes'),
	 ('INEOS','Mercedes'),
	 ('UBS','Mercedes'),
	 ('Epson','Mercedes'),
	 ('Bose','Mercedes'),
	 ('Tommy Hilfiger','Mercedes'),
	 ('IWC','Mercedes'),
	 ('Hewlett Packard','Mercedes'),
	 ('The Ritz-Carlton','Mercedes'),
	 ('Monster Energy','Mercedes');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Pure Storage','Mercedes'),
	 ('CrowdStrike','Mercedes'),
	 ('TIBCO','Mercedes'),
	 ('AMD','Mercedes'),
	 ('Puma','Mercedes'),
	 ('Police','Mercedes'),
	 ('OZ Racing','Mercedes'),
	 ('Endless','Mercedes'),
	 ('Axalta','Mercedes'),
	 ('Belstaff','Mercedes');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Marriott Bonvoy','Mercedes'),
	 ('TeamViewer','Mercedes'),
	 ('Pirelli','Mercedes'),
	 ('Rauch','RBR'),
	 ('Honda','RBR'),
	 ('Mobil 1 Esso','RBR'),
	 ('Puma','RBR'),
	 ('Tag Heuer','RBR'),
	 ('Citrix','RBR'),
	 ('Siemens','RBR');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('AT&T','RBR'),
	 ('Inter','RBR'),
	 ('Hewlett Packard','RBR'),
	 ('Telcel','RBR'),
	 ('Iris','RBR'),
	 ('AlphaTauri','RBR'),
	 ('Hexagon','RBR'),
	 ('DMG Mori','RBR'),
	 ('Ansys','RBR'),
	 ('Sabelt','RBR');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('OZ Racing','RBR'),
	 ('PWR','RBR'),
	 ('Gold Standard','RBR'),
	 ('PRECOR','RBR'),
	 ('Oura','RBR'),
	 ('Claro','RBR'),
	 ('America Movil','RBR'),
	 ('Therabody','RBR'),
	 ('Oracle','RBR'),
	 ('Walmart','RBR');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Pirelli','RBR'),
	 ('British-American Tobacco','McLaren'),
	 ('Splunk','McLaren'),
	 ('DarkTrace','McLaren'),
	 ('Dell','McLaren'),
	 ('Huski Chocolate','McLaren'),
	 ('Gulf','McLaren'),
	 ('Arrow','McLaren'),
	 ('Richard Mille','McLaren'),
	 ('Hilton','McLaren');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Coca Cola','McLaren'),
	 ('Unilever','McLaren'),
	 ('FxPro','McLaren'),
	 ('Deloitte','McLaren'),
	 ('TUMI','McLaren'),
	 ('Iqoniq','McLaren'),
	 ('Mind','McLaren'),
	 ('CNBC','McLaren'),
	 ('Klipsch','McLaren'),
	 ('Sparco','McLaren');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Volvo trucks','McLaren'),
	 ('Enkei','McLaren'),
	 ('Mazak','McLaren'),
	 ('Marelli','McLaren'),
	 ('Ashurst','McLaren'),
	 ('Stratasys','McLaren'),
	 ('Kaust','McLaren'),
	 ('Hookit','McLaren'),
	 ('Alienware','McLaren'),
	 ('Veloce Esports','McLaren');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Ultimotive','McLaren'),
	 ('NEW ERA','McLaren'),
	 ('FAI Aviation Group','McLaren'),
	 ('Buzz & Co','McLaren'),
	 ('Cisco Webex','McLaren'),
	 ('Miory Steel','McLaren'),
	 ('Garena','McLaren'),
	 ('AkzoNobel-Sikkens','McLaren'),
	 ('Logitech G','McLaren'),
	 ('QNTMPAY','McLaren');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Bitci.com','McLaren'),
	 ('Pirelli','McLaren'),
	 ('Cognizant','Aston Martin'),
	 ('Crypto.com','Aston Martin'),
	 ('NetApp','Aston Martin'),
	 ('SentinelOne','Aston Martin'),
	 ('Bombardier','Aston Martin'),
	 ('Girard-Perregaux','Aston Martin'),
	 ('Peroni','Aston Martin'),
	 ('BWT','Aston Martin');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('REPLAY','Aston Martin'),
	 ('Ravenol','Aston Martin'),
	 ('EPOS','Aston Martin'),
	 ('JCB','Aston Martin'),
	 ('EBB3','Aston Martin'),
	 ('UPS Direct','Aston Martin'),
	 ('STL','Aston Martin'),
	 ('Pelmark','Aston Martin'),
	 ('Voip Unlimited','Aston Martin'),
	 ('Condeco','Aston Martin');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('IFS','Aston Martin'),
	 ('Schuberth','Aston Martin'),
	 ('Hackett London','Aston Martin'),
	 ('AlpineStars','Aston Martin'),
	 ('Oakley','Aston Martin'),
	 ('Pirelli','Aston Martin'),
	 ('Castrol','Alpine'),
	 ('RCi','Alpine'),
	 ('MAPFRE','Alpine'),
	 ('bp Ultimate','Alpine');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Dupont','Alpine'),
	 ('Microsoft','Alpine'),
	 ('Bell & Ross','Alpine'),
	 ('Eurodatacar','Alpine'),
	 ('Pirelli','Alpine'),
	 ('GENII','Alpine'),
	 ('Renault E-Tech','Alpine'),
	 ('Yahoo!','Alpine'),
	 ('3D Systems','Alpine'),
	 ('Hewlett-Packard','Alpine');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('PerkinElmer','Alpine'),
	 ('Le coq Sportif','Alpine'),
	 ('GF Matching Solutions','Alpine'),
	 ('Siemens','Alpine'),
	 ('Alpinestars','Alpine'),
	 ('Boeing','Alpine'),
	 ('Elysium','Alpine'),
	 ('GCAPS','Alpine'),
	 ('Hexis','Alpine'),
	 ('Jabil','Alpine');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Linde','Alpine'),
	 ('MATRIX','Alpine'),
	 ('Roland','Alpine'),
	 ('Trak Racer','Alpine'),
	 ('Volume Graphics','Alpine'),
	 ('myWorld','AlphaTauri'),
	 ('Edifice Casio','AlphaTauri'),
	 ('AlphaTauri','AlphaTauri'),
	 ('Honda','AlphaTauri'),
	 ('Randstad','AlphaTauri');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Pirelli','AlphaTauri'),
	 ('RDS','AlphaTauri'),
	 ('Riedel','AlphaTauri'),
	 ('Siemens','AlphaTauri'),
	 ('DAZN','AlphaTauri'),
	 ('Mission Winnow','Ferrari'),
	 ('Ray-Ban','Ferrari'),
	 ('Richard Mille','Ferrari'),
	 ('Kaspersky','Ferrari'),
	 ('UPS','Ferrari');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Weichai','Ferrari'),
	 ('Estrella Galicia 0,0','Ferrari'),
	 ('OMR','Ferrari'),
	 ('MAHLE','Ferrari'),
	 ('Pirelli','Ferrari'),
	 ('Puma','Ferrari'),
	 ('Radiobook','Ferrari'),
	 ('SKF','Ferrari'),
	 ('Vistajet','Ferrari'),
	 ('Marelli','Ferrari');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('NGK Spark Plugs','Ferrari'),
	 ('Brembo','Ferrari'),
	 ('Experis','Ferrari'),
	 ('Riedel','Ferrari'),
	 ('Iveco','Ferrari'),
	 ('Palantir','Ferrari'),
	 ('Bell','Ferrari'),
	 ('Technogym','Ferrari'),
	 ('Alfa Romeo','Ferrari'),
	 ('Garrett','Ferrari');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Shell','Ferrari'),
	 ('Giorgio Armani','Ferrari'),
	 ('Sabelt','Ferrari'),
	 ('Alfa Romeo','Alfa Romeo'),
	 ('PKN Orlen','Alfa Romeo'),
	 ('Adler Pelzer Group','Alfa Romeo'),
	 ('Acer','Alfa Romeo'),
	 ('Built for Athletes','Alfa Romeo'),
	 ('Carrera','Alfa Romeo'),
	 ('Singha','Alfa Romeo');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Additive Industries','Alfa Romeo'),
	 ('IQONIQ','Alfa Romeo'),
	 ('Iveco','Alfa Romeo'),
	 ('Livinguard','Alfa Romeo'),
	 ('Marelli','Alfa Romeo'),
	 ('Mitsubishi Electric','Alfa Romeo'),
	 ('Pirelli','Alfa Romeo'),
	 ('Save the Children','Alfa Romeo'),
	 ('Sparco','Alfa Romeo'),
	 ('Walter Meier','Alfa Romeo');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Zadara','Alfa Romeo'),
	 ('AB Dynamics','Alfa Romeo'),
	 ('Brutsch-Ruegger','Alfa Romeo'),
	 ('Riedel','Alfa Romeo'),
	 ('Uralkali','Haas'),
	 ('1&1','Haas'),
	 ('Alpinestars','Haas'),
	 ('Pirelli','Haas'),
	 ('Schuberth','Haas'),
	 ('Stichd','Haas');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Haas Automation','Haas'),
	 ('Ionos','Haas'),
	 ('Under Armour','Haas'),
	 ('Sofina','Williams'),
	 ('Lavazza','Williams'),
	 ('Acronis','Williams'),
	 ('Versa','Williams'),
	 ('Financial Times','Williams'),
	 ('PONOS','Williams'),
	 ('Symantec','Williams');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('IQONIQ','Williams'),
	 ('Pirelli','Williams'),
	 ('Umbro','Williams'),
	 ('PPG','Williams'),
	 ('Thales','Williams'),
	 ('Precision Hydration','Williams'),
	 ('Crew Clothing','Williams'),
	 ('U-Earth','Williams'),
	 ('Life Fitness','Williams'),
	 ('Spinal Injuries Association (sia)','Williams');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Honibe','Williams'),
	 ('Bremont','Williams'),
	 ('Zeiss','Williams'),
	 ('KX','Williams'),
	 ('DTEX','Williams'),
	 ('B&R','Williams'),
	 ('Nexa 3D','Williams'),
	 ('OMP','Williams'),
	 ('Dynabox','McLaren'),
	 ('Yozio','McLaren');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Wikibox','McLaren'),
	 ('Shuffledrive','McLaren'),
	 ('Cogilith','McLaren'),
	 ('Brightdog','McLaren'),
	 ('Divavu','McLaren'),
	 ('Rhycero','McLaren'),
	 ('Gevee','McLaren'),
	 ('Vinder','McLaren'),
	 ('Eadel','McLaren'),
	 ('Dynabox','McLaren');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Mudo','McLaren'),
	 ('Skilith','McLaren'),
	 ('Twitterlist','McLaren'),
	 ('Yodel','McLaren'),
	 ('Realcube','McLaren'),
	 ('Voomm','McLaren'),
	 ('Feedspan','McLaren'),
	 ('Skipfire','McLaren'),
	 ('Lazzy','McLaren'),
	 ('Quimba','McLaren');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Brainsphere','McLaren'),
	 ('Realmix','McLaren'),
	 ('Mudo','McLaren'),
	 ('Kwilith','McLaren'),
	 ('Meezzy','McLaren'),
	 ('Youbridge','McLaren'),
	 ('Twitterbeat','McLaren'),
	 ('Brightbean','McLaren'),
	 ('Quimm','McLaren'),
	 ('Zoonder','McLaren');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Voomm','McLaren'),
	 ('Viva','McLaren'),
	 ('Flashspan','McLaren'),
	 ('Divape','McLaren'),
	 ('Rhynyx','McLaren'),
	 ('Izio','McLaren'),
	 ('Devpoint','McLaren'),
	 ('Jayo','McLaren'),
	 ('Aivee','McLaren'),
	 ('Geba','McLaren');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Flipopia','McLaren'),
	 ('Youfeed','McLaren'),
	 ('Vipe','McLaren'),
	 ('Trudeo','McLaren'),
	 ('Yozio','McLaren'),
	 ('Meembee','McLaren'),
	 ('Vinte','McLaren'),
	 ('Photojam','McLaren'),
	 ('Plambee','McLaren'),
	 ('Shuffletag','McLaren');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Skidoo','McLaren'),
	 ('BlogXS','McLaren'),
	 ('Wikizz','McLaren'),
	 ('Brightdog','McLaren'),
	 ('Reallinks','McLaren'),
	 ('Flipstorm','McLaren'),
	 ('Meedoo','McLaren'),
	 ('Izio','McLaren'),
	 ('Eadel','McLaren'),
	 ('Youtags','McLaren');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Oba','McLaren'),
	 ('Kazu','McLaren'),
	 ('Rhyloo','McLaren'),
	 ('Livetube','McLaren'),
	 ('Twitterwire','McLaren'),
	 ('Dablist','McLaren'),
	 ('Edgewire','McLaren'),
	 ('Photobug','McLaren'),
	 ('Meeveo','McLaren'),
	 ('Quire','McLaren');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Skyndu','McLaren'),
	 ('Flashpoint','McLaren'),
	 ('Tagpad','McLaren'),
	 ('Eare','McLaren'),
	 ('Gevee','McLaren'),
	 ('Linkbuzz','McLaren'),
	 ('Yambee','McLaren'),
	 ('Eare','McLaren'),
	 ('Meevee','McLaren'),
	 ('Twinte','McLaren');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Babblestorm','McLaren'),
	 ('Flipopia','McLaren'),
	 ('Quimm','McLaren'),
	 ('Tagfeed','McLaren'),
	 ('Skibox','McLaren'),
	 ('Agivu','McLaren'),
	 ('Yoveo','McLaren'),
	 ('Demivee','McLaren'),
	 ('Devshare','McLaren'),
	 ('Podcat','McLaren');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Youfeed','McLaren'),
	 ('Yodo','McLaren'),
	 ('Blogspan','McLaren'),
	 ('Avamm','McLaren'),
	 ('Thoughtmix','McLaren'),
	 ('Reallinks','McLaren'),
	 ('Blogpad','McLaren'),
	 ('Buzzbean','McLaren'),
	 ('Bluejam','McLaren'),
	 ('Realcube','McLaren');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Tagcat','Mercedes'),
	 ('InnoZ','McLaren'),
	 ('Yodel','McLaren'),
	 ('Youtags','McLaren'),
	 ('Tagcat','McLaren'),
	 ('Tazzy','McLaren'),
	 ('Eare','McLaren'),
	 ('Meembee','McLaren'),
	 ('Kanoodle','Aston Martin'),
	 ('Ozu','Aston Martin');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Flipbug','Aston Martin'),
	 ('Meeveo','Aston Martin'),
	 ('Leenti','Aston Martin'),
	 ('Feedfish','Aston Martin'),
	 ('Babbleblab','Aston Martin'),
	 ('Mycat','Aston Martin'),
	 ('Yakitri','Aston Martin'),
	 ('Jamia','Aston Martin'),
	 ('Wordify','Aston Martin'),
	 ('Gabspot','Aston Martin');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Gabspot','Aston Martin'),
	 ('Reallinks','Aston Martin'),
	 ('Skinder','Aston Martin'),
	 ('Edgewire','Aston Martin'),
	 ('Fivebridge','Aston Martin'),
	 ('Trudeo','Aston Martin'),
	 ('Chatterpoint','Aston Martin'),
	 ('Vinder','Aston Martin'),
	 ('Vinder','Aston Martin'),
	 ('Quatz','Aston Martin');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Tagopia','Aston Martin'),
	 ('Topiclounge','Aston Martin'),
	 ('Bubbletube','Aston Martin'),
	 ('Dabfeed','Aston Martin'),
	 ('Chatterpoint','Aston Martin'),
	 ('Lazz','Aston Martin'),
	 ('Gabtype','Aston Martin'),
	 ('Brainverse','Aston Martin'),
	 ('Riffwire','Aston Martin'),
	 ('Skinder','Aston Martin');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Ozu','Aston Martin'),
	 ('Edgetag','Aston Martin'),
	 ('Wikizz','Aston Martin'),
	 ('Jatri','Aston Martin'),
	 ('Kwilith','Aston Martin'),
	 ('Meedoo','Aston Martin'),
	 ('Divanoodle','Aston Martin'),
	 ('Eazzy','Aston Martin'),
	 ('Roomm','Aston Martin'),
	 ('Buzzshare','Aston Martin');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Quimba','Aston Martin'),
	 ('Skyble','Aston Martin'),
	 ('Avavee','Aston Martin'),
	 ('Demizz','Aston Martin'),
	 ('Vinder','Aston Martin'),
	 ('Izio','Aston Martin'),
	 ('Gigabox','Aston Martin'),
	 ('Youbridge','Aston Martin'),
	 ('Fivespan','Aston Martin'),
	 ('Zoomdog','Aston Martin');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Yodel','Aston Martin'),
	 ('Browsedrive','Alfa Romeo'),
	 ('Tekfly','Alfa Romeo'),
	 ('Omba','Alfa Romeo'),
	 ('Photobug','Alfa Romeo'),
	 ('Twitterworks','Alfa Romeo'),
	 ('Twitternation','Alfa Romeo'),
	 ('Yotz','Alfa Romeo'),
	 ('Katz','Alfa Romeo'),
	 ('Chatterpoint','Alfa Romeo');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Twinder','Alfa Romeo'),
	 ('Snaptags','Alfa Romeo'),
	 ('Innojam','Alfa Romeo'),
	 ('Edgewire','Alfa Romeo'),
	 ('Mymm','Alfa Romeo'),
	 ('Gabtune','Alfa Romeo'),
	 ('Skinte','Mercedes'),
	 ('Abatz','RBR'),
	 ('Realfire','RBR'),
	 ('Flipbug','RBR');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Devbug','RBR'),
	 ('Kwideo','RBR'),
	 ('Tagfeed','RBR'),
	 ('Eazzy','RBR'),
	 ('Browsebug','RBR'),
	 ('Geba','RBR'),
	 ('Jaxworks','RBR'),
	 ('Ooba','RBR'),
	 ('Bubblebox','RBR'),
	 ('Topiczoom','RBR');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Tagchat','RBR'),
	 ('Linklinks','RBR'),
	 ('Voonyx','RBR'),
	 ('Jaxbean','RBR'),
	 ('Oyondu','RBR'),
	 ('Centimia','RBR'),
	 ('Zooveo','RBR'),
	 ('Buzzster','RBR'),
	 ('Skidoo','RBR'),
	 ('Jabberstorm','RBR');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Yozio','RBR'),
	 ('Feedfire','RBR'),
	 ('Edgeclub','RBR'),
	 ('Babbleset','RBR'),
	 ('Dablist','RBR'),
	 ('Rhynoodle','RBR'),
	 ('Kamba','RBR'),
	 ('Browsezoom','RBR'),
	 ('Oyoyo','RBR'),
	 ('Cogibox','RBR');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Vitz','RBR'),
	 ('Linktype','Alfa Romeo'),
	 ('Podcat','Alfa Romeo'),
	 ('Yambee','Alfa Romeo'),
	 ('Zooxo','Alfa Romeo'),
	 ('Zoombox','Alfa Romeo'),
	 ('Skyba','Alfa Romeo'),
	 ('Zooxo','Alfa Romeo'),
	 ('Kwimbee','AlphaTauri'),
	 ('JumpXS','AlphaTauri');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Voolia','AlphaTauri'),
	 ('Photobug','AlphaTauri'),
	 ('Wikido','AlphaTauri'),
	 ('Oyope','AlphaTauri'),
	 ('Yambee','AlphaTauri'),
	 ('Flipstorm','AlphaTauri'),
	 ('Quatz','AlphaTauri'),
	 ('Minyx','AlphaTauri'),
	 ('Jaxspan','AlphaTauri'),
	 ('Realpoint','AlphaTauri');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Skiba','AlphaTauri'),
	 ('Mydeo','AlphaTauri'),
	 ('Photojam','AlphaTauri'),
	 ('Myworks','AlphaTauri'),
	 ('Meeveo','AlphaTauri'),
	 ('Yadel','AlphaTauri'),
	 ('Tagopia','AlphaTauri'),
	 ('Photolist','AlphaTauri'),
	 ('Jayo','AlphaTauri'),
	 ('Devpulse','AlphaTauri');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Yombu','AlphaTauri'),
	 ('Devcast','AlphaTauri'),
	 ('Eidel','AlphaTauri'),
	 ('Livetube','AlphaTauri'),
	 ('Flashspan','AlphaTauri'),
	 ('Trilia','AlphaTauri'),
	 ('Tazz','AlphaTauri'),
	 ('Kazio','AlphaTauri'),
	 ('Skajo','AlphaTauri'),
	 ('Kazio','AlphaTauri');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Tanoodle','AlphaTauri'),
	 ('Pixoboo','AlphaTauri'),
	 ('Babbleblab','AlphaTauri'),
	 ('Brightbean','AlphaTauri'),
	 ('Lazzy','AlphaTauri'),
	 ('Zoomzone','AlphaTauri'),
	 ('Skiptube','AlphaTauri'),
	 ('Linkbuzz','AlphaTauri'),
	 ('Shuffletag','AlphaTauri'),
	 ('Riffwire','AlphaTauri');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Oloo','AlphaTauri'),
	 ('Ooba','AlphaTauri'),
	 ('Quimba','AlphaTauri'),
	 ('Kwimbee','AlphaTauri'),
	 ('Jabbertype','AlphaTauri'),
	 ('Brainsphere','AlphaTauri'),
	 ('Katz','AlphaTauri'),
	 ('Riffwire','AlphaTauri'),
	 ('Thoughtmix','AlphaTauri'),
	 ('Rooxo','AlphaTauri');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Yakijo','AlphaTauri'),
	 ('Mymm','AlphaTauri'),
	 ('Rhynyx','AlphaTauri'),
	 ('Blogspan','AlphaTauri'),
	 ('Tagpad','AlphaTauri'),
	 ('Lazz','AlphaTauri'),
	 ('Trudoo','AlphaTauri'),
	 ('Brightdog','AlphaTauri'),
	 ('Trudeo','AlphaTauri'),
	 ('Brainbox','AlphaTauri');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Jaxspan','AlphaTauri'),
	 ('Rhyzio','AlphaTauri'),
	 ('Oyondu','Mercedes'),
	 ('Voonte','Aston Martin'),
	 ('Youspan','Aston Martin'),
	 ('Pixonyx','Aston Martin'),
	 ('Edgewire','Aston Martin'),
	 ('Babbleset','Aston Martin'),
	 ('Pixoboo','Aston Martin'),
	 ('Wikizz','Aston Martin');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Yata','Aston Martin'),
	 ('Gevee','Aston Martin'),
	 ('Chatterbridge','Aston Martin'),
	 ('Tagopia','Aston Martin'),
	 ('Dabtype','Aston Martin'),
	 ('Trunyx','Aston Martin'),
	 ('Pixonyx','Aston Martin'),
	 ('Divavu','Aston Martin'),
	 ('Yombu','Aston Martin'),
	 ('Riffpedia','Aston Martin');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Oyonder','Aston Martin'),
	 ('Voomm','Aston Martin'),
	 ('Minyx','Aston Martin'),
	 ('Voonte','Aston Martin'),
	 ('Skinix','Aston Martin'),
	 ('Topiczoom','Aston Martin'),
	 ('Realbridge','Aston Martin'),
	 ('Tagfeed','Aston Martin'),
	 ('Fivebridge','Aston Martin'),
	 ('Feednation','Aston Martin');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Riffpath','Aston Martin'),
	 ('Meejo','Aston Martin'),
	 ('Kaymbo','Aston Martin'),
	 ('Youfeed','Aston Martin'),
	 ('Thoughtsphere','Aston Martin'),
	 ('Babbleset','Aston Martin'),
	 ('Wikizz','Aston Martin'),
	 ('Tanoodle','Aston Martin'),
	 ('Agivu','Aston Martin'),
	 ('Riffpedia','Aston Martin');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Mita','Aston Martin'),
	 ('Feedspan','Aston Martin'),
	 ('Divanoodle','Aston Martin'),
	 ('Zooveo','Aston Martin'),
	 ('Jabberstorm','Aston Martin'),
	 ('Kazio','Aston Martin'),
	 ('Eabox','Aston Martin'),
	 ('Twinder','Aston Martin'),
	 ('Centidel','Aston Martin'),
	 ('Youspan','Aston Martin');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Mynte','Aston Martin'),
	 ('Feedfish','Aston Martin'),
	 ('Oozz','Aston Martin'),
	 ('Twitterwire','Aston Martin'),
	 ('Camido','Aston Martin'),
	 ('Skidoo','Aston Martin'),
	 ('Devify','Aston Martin'),
	 ('Dynabox','Aston Martin'),
	 ('Livepath','Aston Martin'),
	 ('Kimia','Mercedes');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Skippad','Mercedes'),
	 ('Kwilith','Alpine'),
	 ('Skyndu','Alpine'),
	 ('Gabtype','Alpine'),
	 ('Avaveo','Alpine'),
	 ('Brainlounge','Alpine'),
	 ('Thoughtstorm','Alpine'),
	 ('Cogilith','Alpine'),
	 ('Jabberbean','Alpine'),
	 ('Tagtune','Alpine');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Browsebug','Alpine'),
	 ('Fivespan','Alpine'),
	 ('Reallinks','Alpine'),
	 ('Youfeed','Alpine'),
	 ('Trudeo','Alpine'),
	 ('Kwideo','Alpine'),
	 ('Edgewire','Alpine'),
	 ('Viva','Alpine'),
	 ('Thoughtworks','Alpine'),
	 ('Dabjam','Alpine');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Omba','Alpine'),
	 ('Latz','Alpine'),
	 ('Aimbo','Alpine'),
	 ('Kare','Alpine'),
	 ('Meevee','Alpine'),
	 ('Mymm','Alpine'),
	 ('Yata','Alpine'),
	 ('Mudo','Alpine'),
	 ('Realpoint','Alpine'),
	 ('Twitterworks','Alpine');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Feedspan','Alpine'),
	 ('Thoughtstorm','Alpine'),
	 ('Trudoo','Alpine'),
	 ('Jabbersphere','Alpine'),
	 ('Photofeed','Alpine'),
	 ('Browsezoom','Alpine'),
	 ('Tavu','Alpine'),
	 ('Skinix','Alpine'),
	 ('Mydeo','Alpine'),
	 ('Muxo','Alpine');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Trilith','Alpine'),
	 ('Wikizz','Alpine'),
	 ('Skyndu','Alpine'),
	 ('Youopia','Alpine'),
	 ('Jayo','Alpine'),
	 ('Minyx','Alpine'),
	 ('Jabbertype','Alpine'),
	 ('Brainverse','Alpine'),
	 ('Tagchat','Alpine'),
	 ('Aimbu','Alpine');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Oodoo','Alpine'),
	 ('Photobug','Alpine'),
	 ('Thoughtbridge','AlphaTauri'),
	 ('Twitterwire','AlphaTauri'),
	 ('Browsebug','AlphaTauri'),
	 ('Fiveclub','AlphaTauri'),
	 ('Skimia','AlphaTauri'),
	 ('Twiyo','AlphaTauri'),
	 ('Photojam','AlphaTauri'),
	 ('Divanoodle','AlphaTauri');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Dabfeed','AlphaTauri'),
	 ('Oyoyo','AlphaTauri'),
	 ('Zoovu','AlphaTauri'),
	 ('Divavu','AlphaTauri'),
	 ('Youfeed','AlphaTauri'),
	 ('Jetwire','AlphaTauri'),
	 ('Camido','AlphaTauri'),
	 ('Voonyx','AlphaTauri'),
	 ('Photobug','AlphaTauri'),
	 ('Eamia','AlphaTauri');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Jamia','AlphaTauri'),
	 ('Riffwire','AlphaTauri'),
	 ('Ntag','AlphaTauri'),
	 ('Mycat','AlphaTauri'),
	 ('Buzzdog','AlphaTauri'),
	 ('Feedfish','AlphaTauri'),
	 ('Realpoint','AlphaTauri'),
	 ('Oyoyo','AlphaTauri'),
	 ('Brainverse','AlphaTauri'),
	 ('Wordware','AlphaTauri');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Shufflester','AlphaTauri'),
	 ('Skilith','AlphaTauri'),
	 ('Einti','AlphaTauri'),
	 ('Skimia','AlphaTauri'),
	 ('Devpoint','AlphaTauri'),
	 ('Divanoodle','AlphaTauri'),
	 ('Avamm','AlphaTauri'),
	 ('Abata','AlphaTauri'),
	 ('Linklinks','AlphaTauri'),
	 ('Tagtune','AlphaTauri');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Feedmix','AlphaTauri'),
	 ('Dabjam','AlphaTauri'),
	 ('Yodoo','AlphaTauri'),
	 ('Rhyloo','AlphaTauri'),
	 ('Twitterbridge','AlphaTauri'),
	 ('Gevee','AlphaTauri'),
	 ('Fivebridge','AlphaTauri'),
	 ('Flipbug','Mercedes'),
	 ('Bubblemix','Mercedes'),
	 ('Jabberstorm','Mercedes');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Riffpath','Mercedes'),
	 ('Photojam','Mercedes'),
	 ('Ozu','Mercedes'),
	 ('Fadeo','Mercedes'),
	 ('Geba','Mercedes'),
	 ('Fatz','Mercedes'),
	 ('Flashdog','Mercedes'),
	 ('Kazio','Mercedes'),
	 ('Katz','Mercedes'),
	 ('Cogidoo','Ferrari');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Zooxo','Ferrari'),
	 ('Zoonoodle','Ferrari'),
	 ('Oyonder','Ferrari'),
	 ('Buzzdog','Ferrari'),
	 ('Jamia','Ferrari'),
	 ('Voonder','Ferrari'),
	 ('Oyondu','Ferrari'),
	 ('Zoombeat','Ferrari'),
	 ('Trilia','Ferrari'),
	 ('Chatterpoint','Ferrari');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Quinu','Ferrari'),
	 ('Aibox','Ferrari'),
	 ('Vitz','Ferrari'),
	 ('Tagfeed','Ferrari'),
	 ('Dabjam','Ferrari'),
	 ('Divanoodle','Ferrari'),
	 ('Muxo','Ferrari'),
	 ('Flipbug','Ferrari'),
	 ('Rhycero','Ferrari'),
	 ('Skynoodle','Ferrari');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Wordtune','Ferrari'),
	 ('Topicshots','Ferrari'),
	 ('Fatz','Ferrari'),
	 ('Thoughtsphere','Ferrari'),
	 ('Avamm','Ferrari'),
	 ('Bubblebox','Ferrari'),
	 ('Jetwire','Ferrari'),
	 ('Wikibox','Ferrari'),
	 ('Katz','Ferrari'),
	 ('Quire','Ferrari');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Feedfish','Ferrari'),
	 ('Topicblab','Ferrari'),
	 ('Divape','Ferrari'),
	 ('Meevee','Ferrari'),
	 ('Dabfeed','Ferrari'),
	 ('Vimbo','Ferrari'),
	 ('Jabberstorm','Ferrari'),
	 ('Shuffledrive','Ferrari'),
	 ('Bubbletube','Ferrari'),
	 ('Voolith','Ferrari');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Yakidoo','Ferrari'),
	 ('Midel','Ferrari'),
	 ('Kaymbo','Ferrari'),
	 ('Youfeed','Ferrari'),
	 ('Muxo','Ferrari'),
	 ('Livefish','Ferrari'),
	 ('Bluezoom','Ferrari'),
	 ('Meejo','Ferrari'),
	 ('Skipstorm','Ferrari'),
	 ('Skidoo','Ferrari');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Mybuzz','Ferrari'),
	 ('Feedfish','Ferrari'),
	 ('Divavu','Ferrari'),
	 ('Demizz','Ferrari'),
	 ('Photojam','Ferrari'),
	 ('Wikizz','Ferrari'),
	 ('Riffpath','Ferrari'),
	 ('Kanoodle','Ferrari'),
	 ('Quimba','Ferrari'),
	 ('Topicware','Ferrari');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Skimia','Ferrari'),
	 ('Vitz','Ferrari'),
	 ('Roodel','Ferrari'),
	 ('Flashdog','Ferrari'),
	 ('Yombu','Ferrari'),
	 ('Minyx','Ferrari'),
	 ('Yakidoo','Ferrari'),
	 ('Skinder','Ferrari'),
	 ('Yombu','Ferrari'),
	 ('Skyble','Ferrari');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Voonte','Ferrari'),
	 ('Mudo','Ferrari'),
	 ('Gigazoom','Ferrari'),
	 ('Skyba','Ferrari'),
	 ('Zoonder','Ferrari'),
	 ('Edgeify','Ferrari'),
	 ('Tagopia','Ferrari'),
	 ('Devpoint','Ferrari'),
	 ('Yadel','Ferrari'),
	 ('Oyoba','Ferrari');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Edgeify','Ferrari'),
	 ('Trilith','Ferrari'),
	 ('Photobug','Ferrari'),
	 ('Gabcube','Ferrari'),
	 ('Kamba','Ferrari'),
	 ('Jaloo','Ferrari'),
	 ('Cogilith','Ferrari'),
	 ('Podcat','Ferrari'),
	 ('Tagfeed','Ferrari'),
	 ('Buzzster','Ferrari');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Skyba','Ferrari'),
	 ('Yodel','Ferrari'),
	 ('Realpoint','Ferrari'),
	 ('Fivebridge','Ferrari'),
	 ('Pixoboo','Ferrari'),
	 ('Pixoboo','Ferrari'),
	 ('Roomm','Ferrari'),
	 ('Leexo','Ferrari'),
	 ('Quire','Ferrari'),
	 ('Fadeo','RBR');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Zoombeat','RBR'),
	 ('Photospace','RBR'),
	 ('Zooxo','RBR'),
	 ('Edgetag','RBR'),
	 ('JumpXS','RBR'),
	 ('Oyonder','RBR'),
	 ('Dabfeed','RBR'),
	 ('Blogtag','RBR'),
	 ('Dabtype','RBR'),
	 ('Twimm','RBR');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Zoozzy','RBR'),
	 ('Vimbo','RBR'),
	 ('Shufflebeat','RBR'),
	 ('Tagfeed','RBR'),
	 ('Trudoo','RBR'),
	 ('Innotype','RBR'),
	 ('Flashpoint','RBR'),
	 ('Geba','RBR'),
	 ('Quinu','RBR'),
	 ('Abata','RBR');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Viva','RBR'),
	 ('Oba','RBR'),
	 ('Topiclounge','RBR'),
	 ('Twitterbeat','RBR'),
	 ('Twitterbeat','RBR'),
	 ('Skilith','RBR'),
	 ('Zazio','RBR'),
	 ('Brainlounge','RBR'),
	 ('Thoughtsphere','RBR'),
	 ('Yakidoo','RBR');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Demimbu','RBR'),
	 ('Ailane','RBR'),
	 ('Skinix','RBR'),
	 ('Dabvine','RBR'),
	 ('Oozz','RBR'),
	 ('Eimbee','RBR'),
	 ('Thoughtbeat','RBR'),
	 ('Flashspan','RBR'),
	 ('Tekfly','RBR'),
	 ('Ntags','RBR');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Skinder','RBR'),
	 ('Teklist','RBR'),
	 ('Podcat','RBR'),
	 ('Vidoo','RBR'),
	 ('Quimba','RBR'),
	 ('Talane','RBR'),
	 ('Cogidoo','RBR'),
	 ('Flashset','RBR'),
	 ('Tagtune','RBR'),
	 ('Livetube','RBR');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Avavee','RBR'),
	 ('Yodo','RBR'),
	 ('Avavee','RBR'),
	 ('Brainsphere','RBR'),
	 ('Tagfeed','RBR'),
	 ('Oozz','RBR'),
	 ('Voolia','RBR'),
	 ('Rhycero','RBR'),
	 ('Wordify','RBR'),
	 ('Mita','RBR');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Mymm','RBR'),
	 ('Yodoo','RBR'),
	 ('Thoughtstorm','RBR'),
	 ('Skalith','RBR'),
	 ('Pixope','RBR'),
	 ('Buzzshare','RBR'),
	 ('Oyope','RBR'),
	 ('Divavu','RBR'),
	 ('Kwilith','RBR'),
	 ('Rhyloo','RBR');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Rhynoodle','RBR'),
	 ('Mynte','RBR'),
	 ('Rooxo','RBR'),
	 ('Yombu','RBR'),
	 ('Minyx','Alpine'),
	 ('Eabox','Alpine'),
	 ('Jetwire','Alpine'),
	 ('Eire','Alpine'),
	 ('Aivee','Alpine'),
	 ('Jaloo','Alpine');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Trudeo','Alpine'),
	 ('Realpoint','Alpine'),
	 ('Blognation','Alpine'),
	 ('Twimm','Alpine'),
	 ('Bluezoom','Alpine'),
	 ('Rhynyx','Alpine'),
	 ('Dynazzy','Alpine'),
	 ('Blogtags','Alpine'),
	 ('Eazzy','Alpine'),
	 ('Skinder','Alpine');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Einti','Alpine'),
	 ('Gigashots','Alpine'),
	 ('Twiyo','Alpine'),
	 ('Demizz','Alpine'),
	 ('Photobug','Alpine'),
	 ('Skynoodle','Alpine'),
	 ('Fanoodle','Alpine'),
	 ('Oloo','Alpine'),
	 ('Wikivu','Alpine'),
	 ('Blogtags','Alpine');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Flashdog','Alpine'),
	 ('Jabbercube','Alpine'),
	 ('Skyba','Alpine'),
	 ('Kaymbo','Alpine'),
	 ('Twimm','Alpine'),
	 ('Blogspan','Alpine'),
	 ('Livetube','Alpine'),
	 ('Meezzy','Alpine'),
	 ('Digitube','Alpine'),
	 ('Demivee','Alpine');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Avamba','Alpine'),
	 ('Rhycero','Alpine'),
	 ('Edgepulse','Alpine'),
	 ('Realbuzz','Alpine'),
	 ('Wikido','Alpine'),
	 ('Shuffledrive','Alpine'),
	 ('Einti','Alpine'),
	 ('Fivechat','Alpine'),
	 ('Camido','Alpine'),
	 ('Topicblab','Alpine');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Skyble','Alpine'),
	 ('Topiczoom','Alpine'),
	 ('Meejo','Alpine'),
	 ('Meedoo','Alfa Romeo'),
	 ('Tagchat','Alfa Romeo'),
	 ('Topicshots','Alfa Romeo'),
	 ('Avaveo','Alfa Romeo'),
	 ('Oyope','Alfa Romeo'),
	 ('Trilia','Alfa Romeo'),
	 ('Ozu','Alfa Romeo');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Bubblebox','Alfa Romeo'),
	 ('Skippad','Alfa Romeo'),
	 ('Yamia','Alfa Romeo'),
	 ('Thoughtstorm','Alfa Romeo'),
	 ('Ailane','Alfa Romeo'),
	 ('Twimbo','Alfa Romeo'),
	 ('Rhyloo','Alfa Romeo'),
	 ('Brightdog','Alfa Romeo'),
	 ('Zazio','Alfa Romeo'),
	 ('Eabox','Alfa Romeo');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Plambee','Alfa Romeo'),
	 ('Bluejam','Alfa Romeo'),
	 ('Ozu','Alfa Romeo'),
	 ('Tekfly','Alfa Romeo'),
	 ('Pixoboo','Alfa Romeo'),
	 ('Quatz','Alfa Romeo'),
	 ('Jabbercube','Alfa Romeo'),
	 ('Fivebridge','Alfa Romeo'),
	 ('Kwimbee','Alfa Romeo'),
	 ('Oyoloo','Alfa Romeo');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Geba','Alfa Romeo'),
	 ('Quimba','Alfa Romeo'),
	 ('Tazzy','Alfa Romeo'),
	 ('Mydeo','Alfa Romeo'),
	 ('Oyoloo','Alfa Romeo'),
	 ('Devshare','Alfa Romeo'),
	 ('Dynava','Alfa Romeo'),
	 ('Quire','Alfa Romeo'),
	 ('Gigazoom','Alfa Romeo'),
	 ('Shufflebeat','Alfa Romeo');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Skinder','Alfa Romeo'),
	 ('Kaymbo','Alfa Romeo'),
	 ('Devshare','Alfa Romeo'),
	 ('Bluejam','Alfa Romeo'),
	 ('Yombu','Alfa Romeo'),
	 ('Skyble','Alfa Romeo'),
	 ('Jayo','Alfa Romeo'),
	 ('Flashdog','Alfa Romeo'),
	 ('Jayo','Alfa Romeo'),
	 ('Snaptags','Alfa Romeo');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Fliptune','Alfa Romeo'),
	 ('Tazzy','Alfa Romeo'),
	 ('Ntags','Alfa Romeo'),
	 ('Jabberbean','Alfa Romeo'),
	 ('Topicblab','Alfa Romeo'),
	 ('Wikibox','Alfa Romeo'),
	 ('Mynte','Alfa Romeo'),
	 ('Eadel','Alfa Romeo'),
	 ('Skinte','Alfa Romeo'),
	 ('Oodoo','Alfa Romeo');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('BlogXS','Alfa Romeo'),
	 ('Oozz','Alfa Romeo'),
	 ('Yombu','Alfa Romeo'),
	 ('Mydeo','Alfa Romeo'),
	 ('Feedfish','Alfa Romeo'),
	 ('Riffpath','Alfa Romeo'),
	 ('Quimba','Alfa Romeo'),
	 ('Thoughtsphere','Alfa Romeo'),
	 ('Aivee','Alfa Romeo'),
	 ('Youfeed','Alfa Romeo');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Jabbercube','Alfa Romeo'),
	 ('Npath','Alfa Romeo'),
	 ('Podcat','Alfa Romeo'),
	 ('Demimbu','Alfa Romeo'),
	 ('Photobug','Alfa Romeo'),
	 ('Snaptags','Alfa Romeo'),
	 ('Zoovu','Alfa Romeo'),
	 ('Dabshots','Alfa Romeo'),
	 ('Avaveo','Alfa Romeo'),
	 ('Feedfire','Alfa Romeo');
INSERT INTO public.patrocinador (patrocinador,fk_equipe) VALUES
	 ('Tazzy','Alfa Romeo'),
	 ('Skinte','Alfa Romeo'),
	 ('Pixope','Alfa Romeo'),
	 ('Thoughtblab','Alfa Romeo'),
	 ('Eadel','Alfa Romeo'),
	 ('Skivee','Alfa Romeo'),
	 ('Twitterlist','Alfa Romeo'),
	 ('Dabtype','Alfa Romeo'),
	 ('Skyndu','Alfa Romeo'),
	 ('Latz','Alfa Romeo');